package at.aau.entity;

public enum BuildResult {
	SUCCESS,
    DEPENDENCY_RESOLUTION_FAILED,
    TEST_EXECUTION_FAILED,
    COMPILATION_FAILED,
    POM_PARSING_FAILED,
    GOAL_FAILED,
    NO_PARENT_FAILED,
    CYCLIC_DEPENDENCIES_FAILED,
    PLUGIN_DEPENDENCIES_FAILED,
    NO_CHILD_FAILED,
    MALFORMED_VERSION_FAILED,
    UNKNOWN_FAILED,
    NO_POM_AVAILABLE,
    NO_LOG,
    TRAVIS_ABORT,
    FAILED_AFTER_MAVEN,
    FAILED_BEFORE_MAVEN,
    MULTI_MAVEN_COMMAND,
    TRAVIS_CANCELLED;
}
