package at.aau.entity;

public enum JobType {
	IMPORT,CHANGE_GENERATION,WORKKITEM_EXTRACTION,BUILD_RESULT_IMPORT,ISSUE_TYPE_IMPORT, EXPORT_CHANGES, EXPORT_ALL_CHANGES, GENERATE_PBCC,DO_ALL, REIMPORT_BUILD_RESULTS, EXPORT_BUILD_RESULTS, IMPORT_JARS, UPDATE_REPOSITORY, IMPORT_BUILD_RESULTS, DO_INTELLIGENTLY, EXTRACT_COMMIT_PAIRS, EXTRACT_CLASSES
}
